name: Terraform on Main Push

on:
  push:
    branches:
      - main
env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_DEFAULT_REGION: 'us-east-1'
    CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}

jobs:
  
  
  Build_and_Push_Docker_Image_to_DockerHub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          cd Landing-Page-React
          docker build -t olumayor99/doyenify-devops .

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker push olumayor99/doyenify-devops

  Deploy_Infrastructure:
    needs: [Build_and_Push_Docker_Image_to_DockerHub]
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.8

    - name: Inititialize Infra Code
      run: terraform -chdir=Infra init -upgrade

    - name: Format Infra Code
      run: terraform -chdir=Infra fmt

    - name: Deploy Infra
      run: terraform -chdir=Infra apply -auto-approve

  Deploy_Microservices:
    needs: [Deploy_Infrastructure]
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin
    
    - name: Update KUBECONFIG
      run: |
        aws eks update-kubeconfig --region $AWS_DEFAULT_REGION --name $CLUSTER_NAME

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.8

    - name: Inititialize Microservices Code
      run: terraform -chdir=Deployment init -upgrade

    - name: Format Microservices Code
      run: terraform -chdir=Deployment fmt

    - name: Deploy Microservices
      run: terraform -chdir=Deployment apply -auto-approve
